# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./dashboard /app

# Install any needed packages specified in requirements.txt
#RUN add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
RUN apt update
RUN apt install -y gdal-bin
RUN apt install -y libgdal-dev
ENV CPLUS_INCLUDE_PATH /usr/include/gdal
ENV C_INCLUDE_PATH /usr/include/gdal
RUN pip install -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP app.py

# Run the Flask app
CMD ["python import_data.py" && "python app.py"]